version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'dist/*'